my_databricks_profile:
  target: dev
  outputs:
    dev:
      type: databricks
      connection: "databricks-conn"
      host: "adb-5322429995921474.14.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/6b6f1509399b1b43"
      token: "dapie189a977f5f98134dd39259efd6c16cd-2"
      schema: "default"
      location: EU
